CREATE DATABASE IF NOT EXISTS phpq;

USE phpq;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    user_id INT NOT NULL,
    email VARCHAR(255) NOT NULL
);
